// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/decore-arts/LandingPage.tsx": () => import("../components/mockups/decore-arts/LandingPage.tsx"),
  "./components/mockups/decore-arts/SurpriseDarkWood.tsx": () => import("../components/mockups/decore-arts/SurpriseDarkWood.tsx"),
  "./components/mockups/decore-arts/SurpriseHandmade.tsx": () => import("../components/mockups/decore-arts/SurpriseHandmade.tsx"),
  "./components/mockups/decore-arts/SurprisePhotoFirst.tsx": () => import("../components/mockups/decore-arts/SurprisePhotoFirst.tsx"),
  "./components/mockups/decore-arts/VibeEditorial.tsx": () => import("../components/mockups/decore-arts/VibeEditorial.tsx"),
  "./components/mockups/decore-arts/VibeRomantica.tsx": () => import("../components/mockups/decore-arts/VibeRomantica.tsx"),
  "./components/mockups/decore-arts/VibeRustica.tsx": () => import("../components/mockups/decore-arts/VibeRustica.tsx")
};
